build:
  dependencies:
    override:
      - "pip install -r requirements.txt -r requirements-test.txt"
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - py-scrutinizer-run
