build:
  environment:
    python: 3.7.7
  dependencies:
    override:
      - "pip install -r requirements.txt -r requirements-test.txt"
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - py-scrutinizer-run
checks:
  python:
    duplicate_code: false
