language: python
python:
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - redis-server
install:
  - "pip install tox"
before_script:
  - psql -U postgres -c "CREATE DATABASE byceps_test;"
  - psql -U postgres -c "CREATE ROLE byceps_test WITH LOGIN PASSWORD 'test';"
script:
  - "cd webapp"
  - tox
sudo: false
notifications:
  email: false
