language: python
python:
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    packages:
      - language-pack-de
services:
  - redis-server
install:
  - "pip install psycopg2"
before_script:
  - psql -U postgres -c "CREATE DATABASE byceps_test;"
  - psql -U postgres -c "CREATE ROLE byceps_test WITH LOGIN PASSWORD 'test';"
script:
  - "python setup.py test"
sudo: false
notifications:
  email: false
