language: python
python:
  - "3.7"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - language-pack-de
services:
  - redis-server
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt -r requirements-development.txt"
before_script:
  - psql -U postgres -c "CREATE DATABASE byceps_test;"
  - psql -U postgres -c "CREATE ROLE byceps_test WITH LOGIN PASSWORD 'test';"
script:
  - "pytest"
dist: bionic
sudo: false
notifications:
  email: false
