language: python
python:
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - redis-server
install:
  - "pip install tox"
env:
  - DATABASE_URI=postgresql+pg8000://postgres:@127.0.0.1/byceps_test
before_script:
  - psql -c 'CREATE DATABASE byceps_test;' -U postgres
script:
  - "cd webapp"
  - tox
sudo: false
