[build-system]
requires = [
    "setuptools >= 50.1.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ['py37']

[tool.pytest.ini_options]
addopts = "-vv -ra"
testpaths = ["tests/unit", "tests/integration"]
