[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ['py37']

[tool.poetry]
name = "byceps"
version = "0.0"
description = "the Bring-Your-Computer Event Processing System"
authors = ["Jochen Kupperschmidt"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://byceps.nwsnet.de/"

[tool.poetry.dependencies]
python = "^3.7"
bbcode = "^1.0.33"
blinker = "^1.4"
click = ">=7.0, <8.0"
Flask = "^1.1.1"
Flask-SQLAlchemy = "^2.4.0"
hiredis = "^1.0.1"
Jinja2 = "^2.11.1"
"marrow.mailer" = "^4.0.2"
marshmallow = "^3.4.0"
pendulum = "^2.0.5"
pick = "^0.6.4"
Pillow = ">=6.2.2"
psycopg2-binary = "^2.8.2"
ranger = "^0.10"
redis = "^3.3.11"
rq = "^1.1.0"
rq-dashboard = "^0.6.1"
SQLAlchemy = "^1.3.13"
Werkzeug = "^1.0.0"
WTForms = "^2.2.1"

[tool.poetry.dev-dependencies]
black = "19.3b0"
Flask-DebugToolbar = "0.10.1"
flask-shell-ipython = "0.4.1"
freezegun = "0.3.12"
mypy = "0.761"
pytest = "^5.2.1"
python-dotenv = "0.9.1"
Sphinx = "2.1.1"
