[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ['py37']

[tool.poetry]
name = "byceps"
version = "0.0"
description = "the Bring-Your-Computer Event Processing System"
authors = ["Jochen Kupperschmidt"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://byceps.nwsnet.de/"

[tool.poetry.dependencies]
python = "^3.7"
bbcode = "^1.1.0"
blinker = "^1.4"
click = ">=7.0, <8.0"
Flask = "^1.1.2"
Flask-SQLAlchemy = "^2.4.0"
hiredis = "^1.0.1"
Jinja2 = "^2.11.2"
"marrow.mailer" = "^4.0.2"
marshmallow = "^3.5.2"
pendulum = "^2.1.0"
pick = "^0.6.7"
Pillow = "7.1.2"
psycopg2-binary = "^2.8.5"
redis = "^3.5.0"
requests = "^2.23.0"
rq = "^1.3.0"
rq-dashboard = "^0.6.1"
SQLAlchemy = "^1.3.16"
Werkzeug = "^1.0.1"
WTForms = "^2.3.1"

[tool.poetry.dev-dependencies]
black = "19.10b0"
Flask-DebugToolbar = "0.11.0"
flask-shell-ipython = "0.4.1"
freezegun = "0.3.15"
mypy = "0.770"
pytest = "^5.4.1"
python-dotenv = "0.13.0"
requests-mock = "1.8.0"
Sphinx = "2.1.1"
