[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ['py37']

[tool.poetry]
name = "byceps"
version = "0.0"
description = "the Bring-Your-Computer Event Processing System"
authors = ["Jochen Kupperschmidt"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://byceps.nwsnet.de/"

[tool.poetry.dependencies]
python = "^3.7"
